import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: {
      default: "Auth",
      template: "%s | e-com"
    },
    description: 'Generated by NextJS14',
};

export default function layout({children}: {children: React.ReactNode}) {
    return (
        <>
            {children}
        </>
    )
}
