import { auth } from '@/auth';
import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import Link from 'next/link';
import ContactForm from '@/components/contact/contact-form';
import ContactInfo from '@/components/contact/contact-info';

export const metadata: Metadata = {
    title: "Contact",
    description: 'Generated by NextJS14',
};

export default async function ContactPage() {

    const session = await auth();

    const user = session?.user;

    if (!user?.email) {
        return redirect("/api/auth/signin");
    };

    return (
        <div className='flex flex-row items-center justify-around w-full min-h-screen bg-gradient-to-bl 
            from-sky-100 from-10% text-slate-700 to-slate-100 to-90%'>

            <div className='absolute top-3 right-3 z-20'>
                <li className='list-none text-orange-500 hover:text-orange-600 active:text-orange-700 rounded'>
                    <Link href="/products">Back to Products 👉</Link>
                </li>
            </div>

            <div className='flex items-center justify-center w-full h-screen px-20 2xl:px-[22%]'>

                <div className='flex flex-row items-center justify-around w-full bg-gradient-to-bl from-slate-700 to-cyan-800 p-10 gap-10 rounded-lg shadow-out'>

                    <div className='flex flex-col items-center w-[45%] min-w-[400px] max-w-[400px] h-auto p-8 pt-4 bg-white rounded-lg shadow-in'>
                        
                        <div className='flex items-start justify-start w-full'>
                            <h2 className="text-3xl text-slate-700/70">
                                Contact
                            </h2>
                        </div>

                        <ContactInfo />

                    </div>

                    <div className='flex flex-col items-center w-[45%] min-w-[400px] max-w-[400px] h-auto p-8 pt-4 bg-white rounded-lg shadow-in'>
                    
                        <div className='flex items-start justify-start w-full'>
                            <h2 className="text-3xl text-slate-700/70">
                                Send a message
                            </h2>
                        </div>

                        <ContactForm user={user} />

                    </div>

                </div>
            </div>
        </div>
    )
};
