import type { Metadata } from "next";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import FormAddress from "@/components/shipping/form-address";

export const metadata: Metadata = {
    title: "Shipping",
    description: 'Generated by NextJS14',
};

export default async function AddressPage() {

    const session = await auth();
    const user = session?.user;

    if (!user?.id) {
        return redirect("/api/auth/signin");
    };

    return (
        <FormAddress />
    )
};