import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react'
import ReactQueryProvider from "./ReactQueryProvider";
import { Toaster } from "react-hot-toast";
import "./globals.css";
//import { Inter } from "next/font/google";
//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Home",
    template: "%s | e-com"
  },
  description: 'Generated by NextJS14',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body>
          <main>
            <ReactQueryProvider>
              {children}
            </ReactQueryProvider>
            <Toaster position="bottom-center" /> 
          </main>
        </body>
      </html>
    </SessionProvider>
  );
}
