import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: {
      absolute: "Place Order"
    },
    description: 'Generated by NextJS14',
};

export default function PlaceOrder() {
    return (
        <div className='flex flex-row items-center justify-around w-full min-h-screen text-black bg-slate-100 p-4'>
            
            <div className='flex flex-col items-center justify-center w-[40%] h-[100%] bg-black m-auto'>
                <div className='bg-cyan-400'>
                    <h2>Payment</h2>
                </div>

                <div className='flex w-full h-full bg-cyan-400'>
                    <div className='flex flex-col items-center justify-evenly w-full h-[240px] bg-blue-500 m-4'>
                        <p className='bg-slate-200'>1</p>
                        <p className='bg-slate-200'>2</p>
                    </div>
                </div>

                <div className='flex w-full h-full bg-red-400'>
                    <div className='flex flex-col items-center justify-evenly w-full h-[240px] bg-blue-500 m-4'>
                        <p className='bg-slate-200'>3</p>
                        <p className='bg-slate-200'>4</p>
                    </div>
                </div>
            </div>

            <div className='flex flex-col items-center justify-center w-[40%] bg-black m-auto'>
                <div className='bg-yellow-400'>
                    <h2>Cart Items</h2>
                </div>

                <div className='bg-yellow-400'>
                    table 1
                </div>

                <div className='bg-yellow-400'>
                    table 2
                </div>
            </div>

        </div>
    )
}
