import type { Metadata } from 'next';
import { auth } from '@/auth';
import { PrismaClient, type Product } from '@prisma/client';
import React, { Suspense } from 'react';
import { redirect } from 'next/navigation';
import ShoppingCartPage from '@/components/products-and-cart/ShoppingCart';
import Loader from '@/components/Loader';

export const metadata: Metadata = {
    title: "Cart",
    description: 'Generated by NextJS14',
};

type UserType = {
    products: Product[]
};

const prisma = new PrismaClient();

export default async function CartPage() {

    const session = await auth();
    const userSession = session?.user;
    
    if (!userSession?.email) {
        return redirect("/api/auth/signin");
    };
    
    /*
        user is allowed to update quantity with 
        server-action
    */
    const user: UserType | null = await prisma.user.findUnique({
        where: {
            email: userSession.email,
        },
        include: {
            products: {
                orderBy: {
                    id: "asc"
                }
            }
        },
    });
    
    if (!user?.products) {
        throw new Error("Error: server action in cart");
    };

    return (
        <React.Fragment>
            <Suspense fallback={<Loader />}>
                <ShoppingCartPage products={user.products} />
            </Suspense>
        </React.Fragment>
    )
};
