import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: {
      default: "Payment",
      template: "%s | e-com"
    },
    description: 'Generated by NextJS14',
};

export default function PaymentLayout({children} : {children: React.ReactNode}) {
    return (
        <>
            {children}
        </>
    )
}
