import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: {
      default: "Payment",
      template: "%s | e-com"
    },
    description: 'Generated by NextJS14',
};

export default function OrderIdLayout({children}: {children: React.ReactNode}) {
    return (
        <div>
            {children}
        </div>
    )
}
