import type { Metadata } from 'next';
import MethodPage from '@/components/payment/method';

export const metadata: Metadata = {
    title: "Payment",
    description: 'Generated by NextJS14',
};

export default function PaymenMethodPage() {
    return (
        <MethodPage />
    )
};
