import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Address",
    description: 'Generated by NextJS14',
};

export default function AddressLayout({children}: {children: React.ReactNode}) {
    return (
        <>
            {children}
        </>
    )
}
