import type { Metadata } from "next";
import HeaderProducts from "@/components/products-and-cart/HeaderProducts";

export const metadata: Metadata = {
    title: {
      absolute: "Cart | e-com"
    },
    description: 'Generated by NextJS14',
};

export default async function CartLayout({children}: {children: React.ReactNode}) {
    return (
        <div>
            <HeaderProducts />
            {children}
        </div>
    )
}