import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Payment",
    description: 'Generated by NextJS14',
};

export default function OrderIdLayout({children}: {children: React.ReactNode}) {
    return (
        <div>
            {children}
        </div>
    )
}
