import { Product } from "@prisma/client";

export async function GET() {
    const products: Product[] = [
        {            
            id: 1,        
            family: "CPU",        
            img: "/assets/images/cpu/cpu_i3.jpg",        
            name: "i3",        
            version: "7897432",        
            stock: 20,        
            price: 1044,        
            quantity: 0,        
            switcher: false,
            updatedAt: new Date(),
            createdAt: new Date(),
            authorId: null,
        },{
            id: 2,
            family: "CPU",
            img: "/assets/images/cpu/cpu_i5.jpg",
            name: "i5",
            version: "1297432",
            stock: 30,
            price: 1244,
            quantity: 0,
            switcher: false,
            updatedAt: new Date(),
            createdAt: new Date(),
            authorId: null,
        },{
            id: 3,
            family: "CPU",
            img: "/assets/images/cpu/cpu_i7.jpg",
            name: "i7",
            version: "2897433",
            stock: 25,
            price: 1200,
            quantity: 0,
            switcher: false,
            updatedAt: new Date(),
            createdAt: new Date(),
            authorId: null,
        },{
            id: 4,
            family: "CPU",
            img: "/assets/images/cpu/cpu_i9.jpg",
            name: "i9",
            version: "1897111",
            stock: 35,
            price: 1380,
            quantity: 0,
            switcher: false,
            updatedAt: new Date(),
            createdAt: new Date(),
            authorId: null,
        },{
            id: 5,
            family: "RAM",
            img: "/assets/images/ram/msi_ram.png",
            name: "MSI",
            version: "7866432",
            stock: 22,
            price: 1480,
            quantity: 0,
            switcher: false,
            updatedAt: new Date(),
            createdAt: new Date(),
            authorId: null,
        },{
            id: 6,
            family: "RAM",
            img: "/assets/images/ram/asus_ram.png",
            name: "Asus",
            version: "7866432",
            stock: 22,
            price: 2000,
            quantity: 0,
            switcher: false,
            updatedAt: new Date(),
            createdAt: new Date(),
            authorId: null,
        },{
            id: 7,
            family: "RAM",
            img: "/assets/images/ram/patriot_ram.png",
            name: "Patriot",
            version: "2992777",
            stock: 38,
            price: 1230,
            quantity: 0,
            switcher: false,
            updatedAt: new Date(),
            createdAt: new Date(),
            authorId: null,
        }
    ];
    return Response.json(products);
};
